### ISSUE TITLE
System.ArgumentException: Invalid token for impersonation - it cannot be duplicated.

### ISSUE THREAD

**Issue by dyou3** [Antaris/RazorEngine#275]
We started having this issue after recent upgrade to RazorEngine.3.6.6. We have a .NET 4.5.2 app on IIS 8 (Win2012 with latest patches). Our Application Pool runs as a specific user identity in order to access network share. We've had this exact setup running without any issues for over a year, until latest upgrade. We use default RazorEngine configuration. Now, a call to Engine.Razor.RunCompile crashes with this stack trace:
```
System.ArgumentException: Invalid token for impersonation - it cannot be duplicated.
   at System.Security.Principal.WindowsIdentity.CreateFromToken(IntPtr userToken)
   at System.Security.Principal.WindowsIdentity..ctor(SerializationInfo info)
   at RazorEngine.Compilation.CrossAppDomainCleanUp.CleanupHelper.RegisterCleanupPath(String path)
   at RazorEngine.Compilation.ExecutionContextLessThread.ActionConv.Call(Boolean data)
   at RazorEngine.Compilation.ExecutionContextLessThread.CallHelperSafeHelper`2.AsAction()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at RazorEngine.Compilation.ExecutionContextLessThread.DefaultCallAction(Action a)
   at RazorEngine.Templating.DefaultCachingProvider.CacheTemplate(ICompiledTemplate template, ITemplateKey templateKey)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
```

**Comment by matthid** [comment]
Thanks for reporting this.

(If you need a quick workaround) You can workaround with this: 

> Use In-Memory compilation and don't use the build-in cleanup logic (read the end of the [temporary files section](https://github.com/Antaris/RazorEngine#temporary-files)). As you are running on IIS Application Pool your app will get probably get recycled from time to time automatically and you don't need to be careful about memory leaks.

However this needs some further investigation. What we currently do is this:
 * Create a new thread
 * Capture the execution context
 * Use this execution context on various places to fix https://github.com/Antaris/RazorEngine/issues/267 (and it is faster then spinning up a bunch of threads).

I think it should be easy to reproduce the problem by importing https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/ExecutionContextLessThread.cs (shouldn't have any dependencies):

```csharp
ExecutionContext empty;
using (var t = ExecutionContextLessThread.Create())
{
    empty = t.CallFunc(() => ExecutionContext.Capture());
}
ExecutionContext.Run(empty, o => {}, null); // works
ExecutionContext.Run(empty, o => {}, null); // fails on your system
```
(please try to reproduce this)

If we find a way to capture the execution context in a way it works reliably on every system I can integrate and release the fix.

Please try for example:
```csharp
ExecutionContext empty;
using (var t = ExecutionContextLessThread.Create())
{
    empty = t.CallFunc(() => 
    {   
            WindowsImpersonationContext wic = WindowsIdentity.Impersonate(IntPtr.Zero);
            try
            {
                return ExecutionContext.Capture();
            }
            finally
            {
                wic.Undo();
            } 
    });
}
```

If this works for you I need to make several adjustments to make that work cross platform and with isolation, but please test and report back.

**Comment by matthid** [comment]
Note: If you give me a step by step guide how to reproduce this with Visual Studio only, that would also help...

**Comment by dyou3** [comment]
We are currently under schedule pressure, so I was not able to plug your code in, sorry. We applied workaround (set DisableTempFileLocking = true), but it had no effect on our issue - we are getting the same exact errors. This is latest 3.7.0. Is there a different workaround we can try?

**Comment by matthid** [comment]
Sorry I was a bit unclear, you need to use `config.CachingProvider = new DefaultCachingProvider(t => {}` as well (this should fix the issue). DisableTempLocking just makes sure to not slowly fill your temp folder....

**Comment by matthid** [comment]
Actually I'm just trying to build a beta/alpha nuget package which probably will work as well, so you can wait for this as well.

**Comment by matthid** [comment]
Please test with https://www.nuget.org/packages/RazorEngine/3.7.1-alpha1 and report back

**Comment by dyou3** [comment]
The issue is still there in  3.7.1-alpha1 (the stack trace is exactly the same). This has been tested on out-of-the-box default config (DisableTempFileLocking and CachingProvider have not been changed).

**Comment by matthid** [comment]
Ok then I have no more idea and you need to try the workaround with the custom `CachingProvider`

`config.CachingProvider = new DefaultCachingProvider(t => {})`

Once you have more time we may be able to investigate this more deeply

**Comment by sealr** [comment]
Hello, I got this nasty regression when trying the 3.7.0 version for the last Seal Report version.
I had to move back to the 3.4.0.0 we were previously using.
The context is the following: .Net 4.0, IIS/MVC and it does not work only when using the integrated Windows authentication on IIS...
If you need to reproduce it, I may guide you...

**Comment by matthid** [comment]
Yes, being to reproduce this would help.. Is it possible to reproduce this with Visual Studio only? Or even better within a Unit Test (so we do not regress this again in the future)? Providing such a unit test would be awesome! It doesn't even matter if the test is windows-only. I would do the integration work in the test suite if needed.

**Comment by sealr** [comment]
OK, to reproduce it:
You have to download the last source of Seal Report from http://sealreport.codeplex.com/SourceControl/latest
Then compile it to see if you have everything OK.
The razor engine Library is in SealLibrary/SharedLibraries 

The error occurs when executing reports through the Web Report Server (IIS) with the Windows authentication.
-> configure the Web Security by running first the Server Manager application, 
then go in the menu Configuration->Configure Web Security.
Then select the Windows Authentication provider
Edit the security groups and rename the 'Default Group' to 'Administrators' if you are part of the machine 'Adminsitrators' group. Click OK and close the app.
-> then you have to setup your IIS: 
select the Web Report Server project properties.
In the Web properties: switch to Local IIS and 
change the project URL to http://localhost/Seal and the start URL to http://localhost/Seal/Main
then push the button to create your virtual directory.
Using IIS Manager configure the site created by enabling the Authentication to Windows Authentication and disabling all other authentications....

And you are done: 
Running the Web Report Server application will normally shows you 2 reports to execute, when you run a report you should get the exception...(if you have replaced the RazorEngine.dll by the last version).

I hope you are familiar with IIS. Perhaps we can swithc by email if you need more info...

**Comment by ckapatch** [comment]
We've also ran into this problem after upgrading to 3.7.0. It's very hard to reproduce it but it was not an issue before the upgrade from 3.6.4. If I can reproduce it, I will send along instructions on how to as well.

**Comment by matthid** [comment]
> The error occurs only when executing reports through the Web Report Server (IIS) with the Windows authentication.

Thanks for the steps, but is there a way to reproduce/simulate this without IIS, ie as part of a unit test? So I don't break this again in a future update...

**Comment by sealr** [comment]
I do not know, I imagine you have to understand the Windows IIS authentication mode to try to reproduce it without IIS... so it can be difficult and long.

**Comment by rsleggett** [comment]
We also have this issue, when Basic Authentication is enabled

**Comment by oliwa19** [comment]
+1 on having the same issue with the same setup. Everything works great locally running on IIS Express but once the site is deployed to IIS 7 it bombs.

**Comment by MattiLehtinen** [comment]
Having the same issue with 3.7.2 in an environment with Windows authentication but it occurs only on a page which allows anonymous access.

**Comment by matthid** [comment]
I tried to reproduce this by installing IIS, setting up Windows authentication and using some simple RazorEngine code, but I still cannot reproduce this... If someone could send me a simple standalone repro sample, ideally without any additional dependencies, that would be awesome. @ariacom Sorry but I couldn't quite follow your steps because I have no Server Manager on my desktop machine.

**Comment by dasariramacharan** [comment]
I do face the issue when i use the  "Engine.Razor.RunCompile" in an async thread in a different context. I do not get this issue when i use in a sync thread which uses the same context as the ASP.net call.

**Comment by uchitha** [comment]
The issue mentioned by dasariramacharan above can be fixed by using the workaround

```c#
    var config = new TemplateServiceConfiguration { Debug = true };
    config.CachingProvider = new DefaultCachingProvider(t => { });
    Engine.Razor = RazorEngineService.Create(config);
    //Now call the Engine.RunCompile
```
But then the question is the risks assocaited with this approach. Any one can advise?

**Comment by marcin-chwedczuk** [comment]
Hi, I have the same issue on ASP.NET MVC application (.NET 4.5) with Windows Authentication. I was able to reproduce this problem on 'clear' VM with fresh installation of VS Community/Win2012/Fresh IIS installation. Problem is not deterministic sometimes you must iisreset or make up to 100 request to force it to occur. Version 3.6.3 worked just fine for me, problem started to occur after update to 3.6.6. Disabling Windows Authentication fixes problem (but I can't do that). I tried to debug it and it is something in transition between SecurityCriticalSafe and SecuritySafe code.

**Comment by TimTheTinker** [comment]
I'm getting this error intermittently when running an ASP.NET application locally in Visual Studio.

**Comment by ThiloL** [comment]
Any news here with this issue?

**Comment by matthid** [comment]
I try to reproduce from time to time but was still unable to do it. If anyone could provide a (self contained) repro that would be wonderful. I tried but couldn't get the one from above running.

**Comment by oliwa19** [comment]
I think we all know how hard it is to fix an issue we can't reproduce. But we know this error didn't occur in previous versions so is it not possible to revert to the "old" way?

**Comment by matthid** [comment]
@oliwa19 Problem is the "old" way had other problems and you can already get that "old" way via:

```
var config = new TemplateServiceConfiguration();
config.CachingProvider = new DefaultCachingProvider(t => { });
config.DisableTempFileLocking = true;
Engine.Razor = RazorEngineService.Create(config);
```

**Comment by lbargaoanu** [comment]
I think you have a version of [this] (https://gist.github.com/lbargaoanu/1f2547cbbbfa9ee6aa43). There are some links with details. My workaround might not apply, but maybe it will help you somehow :)

**Comment by fredericDelaporte** [comment]
To elaborates on @lbargaoanu  comment, if he has seen right, the trouble is something like:
* start from a fresh remote iis site worker (recycle app pool first), on a windows authenticated site.
* browse the remote iis site on an url causing razor engine to initialize.
* razor engine gets initialized and launch an app domain for templates handling. This app domain seems to inherit the user identity from the request having triggered its initialization
* browse from another workstation on an url which will try to use razor engine
* the app domain handling templates may fail due to its identity being not usable by the current request.

In such case, the fix would be to find a way to get the templates app domain to be "current request user agnostic". Maybe there is a way to launch this app domain without the current user identity (or even the whole request context) to be transmitted to it. (If this is the real cause of the trouble.)

This is a strange trouble though. I run into it with a windows authenticated site which does not impersonate. In such case, I would have guessed that current request user identity would not be transmitted to a created app domain. But unfortunately, it looks like I am wrong on this point.

This give me an idea for another workaround: I will try initializing razor engine in the application start event. From there, we should not get a templates app domain bound to the identity of first request having initialized the engine.

In the other links with details from labargaoanu, this one looks to me as being the more informative (and faster to read):
http://stackoverflow.com/q/8993293/1178314

**Comment by fredericDelaporte** [comment]
Follow up: for now, I am no more reproducing the issue since I have initialized the razor engine from the application start event.
(But now I have added a dependency there. Well, could be worst.)

Here is what I mean by initializing: creating a configured razor engine service, and then storing it for reuse by every request.
(Of course for doing it in a cleaner way, you may delegate its initialization to a dependency manager using a 'singleton' lifetime for Razor engine, if the dependency manager is initialized during app startup too, and if you ensure the dependency manager initialization does also triggers razor engine initialization immediately.)

To be even more explicit on what I mean by initializing, here the code I use (sorry, comments not translated ^^):
>        private static IRazorEngineService GetNewDefaultService()
>        {
>            var config = new FluentTemplateServiceConfiguration(ConfigureDefault);
>            return RazorEngineService.Create(config);
>        }
>
>        private static void ConfigureDefault(IConfigurationBuilder builder)
>        {
>            Configure(builder, TemplatesFolders);
>        }
>
>        private static void Configure(IConfigurationBuilder builder, IEnumerable<string> templateFolders)
>        {
>            builder
>                // Support du non encodage des IHtmlString (HtmlString et MvcHtmlString)
>                .EncodeUsing<HtmlStringFactory>()
>                // Chemins de recherche des templates.
>                .ManageUsing(new ResolvePathTemplateManager(templateFolders));
>        }

**Comment by matthid** [comment]
Following @lbargaoanu can someone try if https://www.nuget.org/packages/RazorEngine/3.7.5-beta1 solved the problem?

**Comment by fredericDelaporte** [comment]
Removing my workaround and using this 3.7.5-beta1 version, I am no more reproducing the issue too.

(About my previous comments, looking at the commit, I have messed things up by writing about app domain, they do not look involved here, sorry.)

**Comment by fredericDelaporte** [comment]
May anyone else confirm the 3.7.5-beta1 fix for its own setup please?

**Comment by marcin-chwedczuk** [comment]
It helps in my case too!
